version: "3.8"

services:
  web:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      TZ: Europe/Copenhagen
    volumes:
      - mysql-data:/var/lib/mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

volumes:
  mysql-data:
